package com.asc.auth.model.enums;

public enum FilterKeys {

	STATUS, CATEGORY, LANG, ORDER_TYPE, ORDER_ID, DATE_GREATER_THAN_EQUALS, DATE_LESS_THAN_EQUAL, ACCOUNT_ID,
	ACCOUNT_ID_IN, CARRIER_TRACKING_ID, RECORD_DATE, FROM_DATE, TO_DATE, SHIPMENT_ID_IN, CARRIER, TRACKING_ID,
	BANNER_GROUP, ACTIVITY, USER_ID, ACTIVITY_CODE, CITY_NAME, SERVICE_NAME, SERVICE_CODE, CENTER_CODE, SERVICE_TYPE,
	FILE_TYPE, ITEM_NAME, ITEM_CODE, FOOD_TYPE, TXN_ID_IN, STATUS_IN, MEAL_TYPE, APPOINTMENT_STATUS_IN,
	APPOINTMENT_DATE_GREATER_THAN_EQUALS, EXPERT_ID, APPOINTMENT_DATE, APPOINTMENT_DATE_LESS_THAN, REPORT_TYPE,
	BUSINESS_TYPE, BUSINESS_NAME, BUSINESS_ID, IMAGE_TITLE, PHOTO_ID, EMOJI, ELIGIBAL_FOR_REWARD, IS_SHOW, FREQUENCY,
	COMMUNITY_SHARED, IS_SEEN, MOBILE_NUMBER, LEADERBOARD_CATEGORY, PHOTO_DAIRY, USER_ID_IN, LATITUDE, LONGITUDE,
	USER_NAME, USER_ID_NOT_IN, POINT_TYPE, PRODUCT_ID_IN, ORDER_NUMBER, ORDER_NUMBER_IN, ZIPCODE_IN, LOB,
	IS_SERVICEABLE, SERVICE_CATEGORY, DELIVER_FROM_DATE, DELIVER_TO_DATE, SHIP_FROM_DATE, SHIP_TO_DATE, WAREHOUSE_ID_IN,
	ACCOUNT_CODE_IN, PRODUCT_NAME_IN, ORDER_NUMBERS_LIST, PRODUCTS_LIST_IN, DOCKET_ID, DOCKET_ID_IN, DELIVERY_IN,
	GATE_ENTRY_NUMBER_IN, WAREHOUSE_IN, CATEGORY_OBND, CATEGORY_OBNI, WORKING_STATUS_IN, NAME_IN, DIVISION_ID_IN,
	CATEGORY_IN, PLANT_IN, VENDOR_ID, VENDOR_ID_IN, CUSTOMER_ID, CUSTOMER_ID_IN, DOCKET_NO, BRANCH_ID_IN, DOCKET_NO_IN,
	PRODUCT_CATEGORY_IN, PRODUCT_UNIT_TYPE_IN, PRODUCT_PACKAGE_TYPE_IN, PRODUCT_SKU_IN, PRODUCT_UPC_IN,
	PRODUCT_STATUS_IN, PRODUCT_CATEGORY_PARENT_IN, PRODUCT_CATEGORY_CHILD_IN, FILE_ID_IN, IS_MANDATORY, ATTRIBUTE_NAME,
	PRODUCT_MATERIAL_TYPE_IN, PO_ID_IN, PO_REF_CODE_IN, REFRENCE_CODE_IN, FLOOR_ID_IN, FLOOR_ID, FLOOR_CODE,
	FLOOR_CODE_IN, WAREHOUSE_CODE, SERIAL_NUMBER_IN, INVENTORY_STATUS_IN, LOCATION_BARCODE_IN, INCIDENT_IN, AUDIT_IN,
	ASN_ID_IN, DISPATCH_BILLING_DOCUMENT, VENDOR_CODE, VENDOR_NAME_IN, RECEIVING_DATE, PUT_AWAY_DATE,
	INVENTORY_QUANTITY_GREATER_THAN, GROUP_BY, RECEIVING_DATE_GREATER_THAN, PUT_AWAY_DATE_GREATER_THAN,
	PRODUCT_BATCH_CODE_IN, PRODUCT_BATCH_CODE, RECEIVING_ID_IN, CONTAINER_IN, PUTAWAY_ID_IN, GRN_ID_IN, CREATED_AT_TYPE,
	PUTAWAY_FROM_DATE, PUTAWAY_TO_DATE, RECEIVE_TO_DATE, RECEIVE_FROM_DATE, EXTERNAL_ORDER_NUMBER_IN, CARRIER_SERVICE,
	CREATED_FROM_DATE, CREATED_TO_DATE, SKU_LIST_IN, DUMMY_FILTER_ONE, DUMMY_FILTER_TWO, PICKLIST_ID_IN,
	SHIPMENT_ORDER_NUMBER, ASSIGNED_TO, STATUS_NOT_IN, LOCATION_ZONE_IN, CHANNEL_ID_IN, IS_MAPPED, TITLE_IN,
	INVENTORY_ID_IN, CHANNEL_PRODUCT_IN, CHANNEL_SKU_IN, VARIANT_IN, DESCRIPTION_IN, LOCATION_BIN_TYPE_IN,
	LOADLIST_ID_IN, CUSTOM_CODE_IN, PRODUCT_EXPIRY_DATE, PRODUCT_MFG_DATE, INVENTORY_QUANTITY_GREATER_THAN_EQUAL_TO,
	LOCATION_BARCODE, PRODUCT_MAPPING_IN, ZONE_IN, EXPENSE_IN, EXPENSE_TYPE_IN, YEAR_IN, REGION_IN, INVOICE_IN,
	EXPENSE_MODE_IN, DESIGNATION_IN, QUICK_CODE_IN, REVENUE_ID_IN, INVOICE_NUMBER, OWNERSHIP_TYPE_IN, CITY, MAPPING_IN,
	BUDGET_IN, VIEW_STATUS, PROJECT_CODE_IN, CREATED_BY, APPROVAL_STATUS, EMPLOYEE_CODE, DEPARTMENT_ID_IN, BUDGET_TYPE,
	WAREHOUSE_TYPE, LOCATION_NAME_IN, LOCATION_TYPE_IN, HOD_ID_IN, VENDOR_INVOICE_IN, REPORTING_IN, PINCODE_IN, ID_IN,
	INVOICE_NUMBER_LIKE, USER_TYPE, SKILL_IN, EXPERIENCE_IN, WALLET_ID
}
